package org.bowssf.gui;


import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import it.uniroma1.lcl.jlt.util.Language;
import org.bowssf.gui.actions.BackActionListener;
import org.bowssf.gui.actions.ClearActionListener;
import org.bowssf.gui.actions.SaveConfigurationActionListener;
import org.bowssf.util.IniConfig;

import javax.swing.*;


/**
 * This class is the interface for the configuration
 *
 * @author Alejandro Borrajo Viéitez
 */
public class ConfigurationGUI extends JFrame {


    private final static IniConfig iniConfig = IniConfig.getInstance();
    private JPanel mainpanel;
    private JTextField levelsJField;
    private JButton saveButton;
    private JButton backButton;
    private JRadioButton forceBabelnetRadioButton;
    private JRadioButton forceJedisRadioButton;
    private JComboBox languageCombobox;
    private JButton clearSelection;
    private ButtonGroup bgroup;
    private PreferenceManagerGUI preferenceManager;


    /**
     * Gets the other framework
     *
     * @return return the other framework
     */
    public PreferenceManagerGUI getPreferenceManager() {
        return preferenceManager;
    }

    /**
     * Gets the level field
     *
     * @return the field
     */
    public JTextField getLevelsJField() {
        return levelsJField;
    }

    /**
     * Gets a radioButton
     *
     * @return a radio button for babelnet force
     */
    public JRadioButton getForceBabelnetRadioButton() {
        return forceBabelnetRadioButton;
    }

    /**
     * Gets a radioButtom
     *
     * @return a radio button for jedis force
     */
    public JRadioButton getForceJedisRadioButton() {
        return forceJedisRadioButton;
    }

    /**
     * Gets a combobox
     *
     * @return a combobox for language
     */
    public JComboBox getLanguageCombobox() {
        return languageCombobox;
    }

    /**
     * Constructor of the class
     *
     * @param preferenceManager the other frame
     */
    public ConfigurationGUI(PreferenceManagerGUI preferenceManager) {
        this.preferenceManager = preferenceManager;

        bgroup = new ButtonGroup();
        bgroup.add(forceJedisRadioButton);
        bgroup.add(forceBabelnetRadioButton);
        int select = 0;
        if (iniConfig.getLanguage() == Language.ES) {
            select = 1;
        }

        levelsJField.setText(Integer.toString(iniConfig.getPreloadingLevels()));
        languageCombobox.setSelectedIndex(select);
        forceJedisRadioButton.setSelected(iniConfig.isForceJedis());
        forceBabelnetRadioButton.setSelected(iniConfig.isForceBabelNet());

        saveButton.addActionListener(new SaveConfigurationActionListener(this));
        backButton.addActionListener(new BackActionListener(mainpanel));
        clearSelection.addActionListener(new ClearActionListener(this.bgroup));
    }

    /**
     * Gets a JPanel
     *
     * @return the mainpanel
     */
    public JPanel getMainpanel() {
        return mainpanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainpanel = new JPanel();
        mainpanel.setLayout(new FormLayout("center:131px:noGrow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:d:noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow"));
        final JLabel label1 = new JLabel();
        label1.setText("Preloading levels");
        CellConstraints cc = new CellConstraints();
        mainpanel.add(label1, cc.xy(1, 1, CellConstraints.CENTER, CellConstraints.DEFAULT));
        levelsJField = new JTextField();
        levelsJField.setHorizontalAlignment(0);
        levelsJField.setText("");
        mainpanel.add(levelsJField, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        saveButton = new JButton();
        saveButton.setText("Save");
        mainpanel.add(saveButton, cc.xy(3, 7));
        backButton = new JButton();
        backButton.setText("Back");
        mainpanel.add(backButton, cc.xy(1, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        forceBabelnetRadioButton = new JRadioButton();
        forceBabelnetRadioButton.setText("Force Babelnet");
        mainpanel.add(forceBabelnetRadioButton, cc.xy(3, 5));
        forceJedisRadioButton = new JRadioButton();
        forceJedisRadioButton.setText("Force jedis");
        mainpanel.add(forceJedisRadioButton, cc.xy(1, 5));
        languageCombobox = new JComboBox();
        languageCombobox.setEditable(false);
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("english");
        defaultComboBoxModel1.addElement("spanish");
        languageCombobox.setModel(defaultComboBoxModel1);
        mainpanel.add(languageCombobox, cc.xy(3, 3));
        clearSelection = new JButton();
        clearSelection.setHorizontalTextPosition(0);
        clearSelection.setIcon(new ImageIcon(getClass().getResource("/icons/clear.png")));
        clearSelection.setText("");
        mainpanel.add(clearSelection, cc.xy(5, 5, CellConstraints.CENTER, CellConstraints.CENTER));
        final JLabel label2 = new JLabel();
        label2.setText("Language");
        mainpanel.add(label2, cc.xy(1, 3));
        label1.setLabelFor(levelsJField);
    }

    /**
     *
     */
    public JComponent $$$getRootComponent$$$() {
        return mainpanel;
    }
}
